# Generated by Django 5.1.2 on 2024-10-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='user',
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
